// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/common.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	model/common.proto

It has these top-level messages:
	SayParam
	Pair
	SayResponse
	SRequest
	SResponse
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RespType int32

const (
	RespType_NONE    RespType = 0
	RespType_ASCEND  RespType = 1
	RespType_DESCEND RespType = 2
)

var RespType_name = map[int32]string{
	0: "NONE",
	1: "ASCEND",
	2: "DESCEND",
}
var RespType_value = map[string]int32{
	"NONE":    0,
	"ASCEND":  1,
	"DESCEND": 2,
}

func (x RespType) String() string {
	return proto.EnumName(RespType_name, int32(x))
}
func (RespType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SayParam struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *SayParam) Reset()                    { *m = SayParam{} }
func (m *SayParam) String() string            { return proto.CompactTextString(m) }
func (*SayParam) ProtoMessage()               {}
func (*SayParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SayParam) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Pair struct {
	Key    int32  `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Values string `protobuf:"bytes,2,opt,name=values" json:"values,omitempty"`
}

func (m *Pair) Reset()                    { *m = Pair{} }
func (m *Pair) String() string            { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()               {}
func (*Pair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Pair) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Pair) GetValues() string {
	if m != nil {
		return m.Values
	}
	return ""
}

type SayResponse struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	// 数组
	Values []string `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
	// map
	Header map[string]*Pair `protobuf:"bytes,3,rep,name=header" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Type   RespType         `protobuf:"varint,4,opt,name=type,enum=model.RespType" json:"type,omitempty"`
}

func (m *SayResponse) Reset()                    { *m = SayResponse{} }
func (m *SayResponse) String() string            { return proto.CompactTextString(m) }
func (*SayResponse) ProtoMessage()               {}
func (*SayResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SayResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SayResponse) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *SayResponse) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SayResponse) GetType() RespType {
	if m != nil {
		return m.Type
	}
	return RespType_NONE
}

type SRequest struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *SRequest) Reset()                    { *m = SRequest{} }
func (m *SRequest) String() string            { return proto.CompactTextString(m) }
func (*SRequest) ProtoMessage()               {}
func (*SRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SResponse struct {
	Value []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *SResponse) Reset()                    { *m = SResponse{} }
func (m *SResponse) String() string            { return proto.CompactTextString(m) }
func (*SResponse) ProtoMessage()               {}
func (*SResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SResponse) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*SayParam)(nil), "model.SayParam")
	proto.RegisterType((*Pair)(nil), "model.Pair")
	proto.RegisterType((*SayResponse)(nil), "model.SayResponse")
	proto.RegisterType((*SRequest)(nil), "model.SRequest")
	proto.RegisterType((*SResponse)(nil), "model.SResponse")
	proto.RegisterEnum("model.RespType", RespType_name, RespType_value)
}

func init() { proto.RegisterFile("model/common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xdd, 0x4a, 0xc3, 0x40,
	0x10, 0x85, 0xdd, 0xe6, 0xc7, 0x74, 0x16, 0x34, 0x2c, 0x45, 0x82, 0x88, 0xa4, 0xf1, 0x26, 0x08,
	0x46, 0x89, 0x20, 0xe2, 0x9d, 0xd8, 0x88, 0x57, 0xb1, 0x6c, 0x7c, 0x81, 0xb5, 0x5d, 0x54, 0x6c,
	0xb2, 0x31, 0x3f, 0xc2, 0xbe, 0xab, 0x0f, 0x23, 0x99, 0xa4, 0x1a, 0xf1, 0x6e, 0xce, 0x9e, 0x39,
	0x87, 0xf9, 0x58, 0x60, 0xb9, 0x5a, 0xcb, 0xcd, 0xf9, 0x4a, 0xe5, 0xb9, 0x2a, 0xa2, 0xb2, 0x52,
	0x8d, 0x62, 0x16, 0xbe, 0x05, 0x47, 0xe0, 0x64, 0x42, 0x2f, 0x45, 0x25, 0x72, 0xe6, 0x82, 0x91,
	0xd7, 0x2f, 0x1e, 0xf1, 0x49, 0x38, 0xe5, 0xdd, 0x18, 0x5c, 0x80, 0xb9, 0x14, 0x6f, 0x55, 0xe7,
	0xbc, 0x4b, 0x8d, 0x8e, 0xc5, 0xbb, 0x91, 0x1d, 0x80, 0xfd, 0x29, 0x36, 0xad, 0xac, 0xbd, 0x09,
	0xae, 0x0f, 0x2a, 0xf8, 0x22, 0x40, 0x33, 0xa1, 0xb9, 0xac, 0x4b, 0x55, 0xd4, 0xf2, 0x7f, 0xe7,
	0x9f, 0xa4, 0xf1, 0x9b, 0x64, 0x57, 0x60, 0xbf, 0x4a, 0xb1, 0x96, 0x95, 0x67, 0xf8, 0x46, 0x48,
	0xe3, 0xe3, 0x08, 0x2f, 0x8c, 0x46, 0x6d, 0xd1, 0x03, 0x2e, 0x24, 0x45, 0x53, 0x69, 0x3e, 0x6c,
	0xb3, 0x13, 0x30, 0x1b, 0x5d, 0x4a, 0xcf, 0xf4, 0x49, 0xb8, 0x17, 0xef, 0x0f, 0xa9, 0x2e, 0xf2,
	0xa4, 0x4b, 0xc9, 0xd1, 0x3c, 0xbc, 0x07, 0x3a, 0xca, 0x8e, 0x79, 0xa6, 0x3d, 0xcf, 0x1c, 0x2c,
	0xbc, 0x03, 0x71, 0x68, 0x4c, 0x87, 0x9a, 0x8e, 0x9e, 0xf7, 0xce, 0xcd, 0xe4, 0x9a, 0x04, 0x3e,
	0x38, 0x19, 0x97, 0x1f, 0xad, 0xac, 0x1b, 0x36, 0x03, 0x6b, 0xa5, 0xda, 0xa2, 0xc1, 0x1a, 0x83,
	0xf7, 0x22, 0x98, 0xc3, 0x34, 0xfb, 0xa1, 0x9f, 0x6d, 0x5b, 0x09, 0xa2, 0xf6, 0xe2, 0xf4, 0x0c,
	0x9c, 0xed, 0x79, 0xcc, 0x01, 0x33, 0x7d, 0x4c, 0x13, 0x77, 0x87, 0x01, 0xd8, 0xb7, 0xd9, 0x5d,
	0x92, 0x2e, 0x5c, 0xc2, 0x28, 0xec, 0x2e, 0x92, 0x5e, 0x4c, 0x9e, 0x6d, 0xfc, 0xb0, 0xcb, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x50, 0x84, 0x4d, 0x13, 0xc6, 0x01, 0x00, 0x00,
}
