global:
    scrape_interval: 15s
    external_labels:
      monitor: 'whisker-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'local'

  - job_name: 'whisker'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.3.156:8085']
        labels:
          group: 'hello'
